version: "3.8"
services:
  marvel_react_app:
    build: ./marvel_react_app
    container_name: marvel_app_c
    ports:
      - '3000:3000'
    volumes:
      - ./marvel_react_app/node_modules
    stdin_open: true
    tty: true